// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	ID       uint64 `json:"id"`       // 用户ID
	Token    string `json:"token"`    // 登录token
	ExpireAt string `json:"expireAt"` // 过期时间
}

type TimeReq struct {
	SleepTime int `form:"sleepTime,optional"` // 用户名
}
type TimeResp struct {
	TranceId string `json:"tranceId"`  // 用户名
	Duration int `json:"duration"`  // 用户名
}
type OrderReq struct {
	GoodsName  string  `json:"goodsName,optional"`  // 商品名称
	GoodsSN    int64   `json:"goodsSN,optional"`    // 商品编号
	OrderSN    string  `json:"orderSN,optional"`    // 订单编号
}

type OrderResp struct {
	Code int    `json:"code"` // 响应码
	Msg  string `json:"msg"`  // 响应信息
}
