// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	ID       uint64 `json:"id"`       // 用户ID
	Token    string `json:"token"`    // 登录token
	ExpireAt string `json:"expireAt"` // 过期时间
}
