// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	health "server-zero/cmd/internal/handler/health"
	user "server-zero/cmd/internal/handler/user"
	"server-zero/cmd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Sign, serverCtx.Token, serverCtx.Cors},
			[]rest.Route{
				{
					// 创建用户
					Method:  http.MethodPost,
					Path:    "/customer",
					Handler: user.CreateCustomerHandler(serverCtx),
				},
				{
					// 用户列表查询
					Method:  http.MethodGet,
					Path:    "/customer-query",
					Handler: user.QueryCustomerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/public/user"),
	)
}
