// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	auth "server-zero/cmd/internal/handler/auth"
	"server-zero/cmd/internal/svc"
	test "server-zero/cmd/internal/handler/test"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 请求时间统计
				Method:  http.MethodGet,
				Path:    "/time",
				Handler: test.TimeHandler(serverCtx),
			},
			{
				// 订单
				Method:  http.MethodPost,
				Path:    "/order",
				Handler: test.OrderHandler(serverCtx),
			},
			{
				// 订单长链接测试
				Method:  http.MethodPost,
				Path:    "/kakrolot_web/yike/submit",
				Handler: test.OrderHandler(serverCtx),
			},
			{
				// 代理IP
				Method:  http.MethodGet,
				Path:    "/ExclusiveProxy/GetIP/",
				Handler: test.ZdyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/test"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Token},
			[]rest.Route{
				{
					// 退出登录
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					// 登录
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/auth"),
	)
}
