config:
  server:
    mode: dev # dev开发环境 test测试环境 prod线上环境
    name: lodge-server
    host: 127.0.0.1
    port: 8080
    prefix: /api
  logger:
    encoding: json
    level: info
    timeLayout: "2006-01-02 15:04:05.000"
    name: logger
    path: ./log
    cap: 10
  database:
    driver: mysql
    username: xianglong
    password: A4622511z3!
    host: rm-uf643031x2y9u6765jo.mysql.rds.aliyuncs.com
    port: 3306
    database: eavesdropper
    maxOpen: 100
    maxIdle: 10
  cache:
    driver: redis
    prefix: dev
    redis:
      addr: r-bp1jjf4dd9lxzgm807pd.redis.rds.aliyuncs.com:6379
      password: A4622511z3!
  oss:
    dirPrefix:
    endpoint: 
    bucketName:
    accessKeyId: 
    accessKeySecret: 
  ai:
    url: http://127.0.0.1:8888/chat
admin_url: http://8.152.204.115:8009

    
