/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getCurrentMachineId(): string
export declare function encrypt(plaintext: string, password: string, machineId: string): string
export declare function decrypt(ciphertext: string, password: string, machineId: string): string
export declare function sum(a: number, b: number): number
