/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'algorithm.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.android-arm64.node')
          } else {
            nativeBinding = require('algorithm-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'algorithm.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.android-arm-eabi.node')
          } else {
            nativeBinding = require('algorithm-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'algorithm.win32-x64-msvc.node')
        )
        console.log("win32-x64-msvc", join(__dirname, 'algorithm.win32-x64-msvc.node'), localFileExisted);
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.win32-x64-msvc.node')
          } else {
            nativeBinding = require('algorithm-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'algorithm.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('algorithm-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'algorithm.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('algorithm-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'algorithm.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./algorithm.darwin-universal.node')
      } else {
        nativeBinding = require('algorithm-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        console.log(join(__dirname, 'algorithm.darwin-x64.node'));
        localFileExisted = existsSync(join(__dirname, 'algorithm.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.darwin-x64.node')
          } else {
            nativeBinding = require('algorithm-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'algorithm.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.darwin-arm64.node')
          } else {
            nativeBinding = require('algorithm-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'algorithm.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./algorithm.freebsd-x64.node')
      } else {
        nativeBinding = require('algorithm-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-x64-musl.node')
            } else {
              nativeBinding = require('algorithm-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-x64-gnu.node')
            } else {
              nativeBinding = require('algorithm-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-arm64-musl.node')
            } else {
              nativeBinding = require('algorithm-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('algorithm-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('algorithm-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('algorithm-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('algorithm-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'algorithm.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./algorithm.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('algorithm-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'algorithm.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./algorithm.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('algorithm-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  // Special fallback for darwin-x64 when module is not found through normal paths
  if (platform === 'darwin' && arch === 'x64') {
    try {
      // Try direct path to darwin-x64 build
      const directPath = join(__dirname, 'darwin-x64/algorithm.darwin-x64.node');
      if (existsSync(directPath)) {
        nativeBinding = require('./darwin-x64/algorithm.darwin-x64.node');
        console.log("Loaded darwin-x64 module from direct path");
      }
    } catch (e) {
      console.error("Failed to load from direct path:", e);
    }
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { getCurrentMachineId, encrypt, decrypt, sum } = nativeBinding

module.exports.getCurrentMachineId = getCurrentMachineId
module.exports.encrypt = encrypt
module.exports.decrypt = decrypt
module.exports.sum = sum
